[package]
name = "rust-journal"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "2.0"
anyhow = "1.0"
home = "0.5"
structopt = "0.3.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
